### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by saruvora** [curds01/MengeUtils#4]
Hi @curds01 , I got your link from the Menge crowd simulator repo, can you provide me the documentation of repo as well (email: saruvora123@gmail.com) ? in order to use Menge and also can you help me out to create my own simulation using menge and read the trajectories of these simulations?

**Comment by curds01** [comment]
This is 10 days old? I only got the email notification of this yesterday. Something strange is going on in github land. Here's what I suggest: this sounds like a long conversation, why don't you email me at `menge@cs.unc.edu` and we can have the discussion there.
